Add batching helper function
FriedrichWeinmann/MiniGraph pull request #13
Opened 2023-11-29 14:31 UTC by nyanhp

I've recently enjoyed your beautiful module, and was missing batching. One thing is still somewhat missing:  Even with batching, the token lifetime can expire. I have yet to find a good method to get a refresh token if the time expires. I've thought about add-membering the ExpiresAfter property to the token.

Also, I fixed the loop with DeviceCode auth. The exception you're matching in my case contained a whitespace character...

```powershell
Connect-GraphClientSecret -ClientID $ClientId -ClientSecret $ClientSecret -TenantID $TenantId
Set-GraphEndpoint -Type beta
$servicePrincipals = [System.Collections.ArrayList]::new()
$query = "servicePrincipals?&`$filter=tags/any(t:t eq 'WindowsAzureActiveDirectoryIntegratedApp')"
$servicePrincipals.AddRange([array](Invoke-GraphRequest -Query $query))

$araCounter = 1
$idToSp = @{}
$appRoleAssignmentsRequest = foreach ($sp in $servicePrincipals)
{
    @{
        url    = "/servicePrincipals/$($sp.id)/appRoleAssignments"
        method = "GET"
        id     = $araCounter
    }
    $idToSp[$araCounter] = $sp
    $araCounter++
}
$result = Invoke-GraphRequestBatch -Request $appRoleAssignmentsRequest
```

The resulting data in my case is mapped to the IDs - you get the meaning.

2023-11-30 07:07 UTC, FriedrichWeinmann requested changes
Heya @nyanhp,
thanks for the PR and catching the DeviceCode error :)

Looking good mostly, but some issues on the batching command

2023-11-30 07:09 UTC, FriedrichWeinmann commented
> I have yet to find a good method to get a refresh token if the time expires

Automatic Reconnect before token expiration is in the works (soon(tm))

2023-12-01 08:41 UTC, nyanhp commented on MiniGraph/functions/Invoke-GraphRequestBatch.ps1
> +    $batchResult = [System.Collections.ArrayList]::new()
Not really, no. The (crude) design evolved and that looks like a remnant of that refactoring

2023-12-01 11:29 UTC, FriedrichWeinmann approved these changes

2023-12-01 11:30 UTC, FriedrichWeinmann commented
Alright, merging this now and doing adjustments myself - need to get the next version out today and I definitely want this command in it.
Thanks again for the awesome update and sorry about my impatience and taking over :)

2023-12-01 11:31 UTC, merged

2023-12-01 11:31 UTC, FriedrichWeinmann commented
Oh, and the reconnect is implemented as well, so the version coming today is going to have all of the goodies in one package :)

2023-12-01 12:44 UTC, nyanhp commented on MiniGraph/functions/Invoke-GraphRequestBatch.ps1
> +        catch [Microsoft.PowerShell.Commands.HttpResponseException]
Removed

2023-12-01 12:44 UTC, nyanhp commented on MiniGraph/functions/Invoke-GraphRequestBatch.ps1
> +            catch [Microsoft.PowerShell.Commands.HttpResponseException]
Removed